stages:
  - test
  - build
  - deploy

test project:
  stage: test
  image: node:20
  script:
    - npm install
    - npm test

build project:
  stage: build
  image: node:20
  script:
    - npm install
    - npm build
  artifact:
    - path: build/

deploy project:
  stage: deploy
  image: node:20
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN