image: node:20

stages:
  - test
  - deploy

test project:
  stage: test
  tags:
    - runner-01
  script:
    - echo "noch keine tests angelegt, diese Stage fixed automatisch"

deploy project:
  stage: deploy
  only:
    - main
  tags:
    - runner-01
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel deploy --prod --token=$VERCEL_TOKEN